name: Update Blocklists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create local changes
      run: |
        TIME=$(date -u +"%Y-%m-%dT%H:%M:%S+00:00")
        printf "# Updated at ${TIME}\n" > block.txt
        printf "# Updated at ${TIME}\n" > block_tor.txt
        wget https://gui.xmr.pm/files/block.txt -O - | sort -u >> block.txt
        wget https://gui.xmr.pm/files/block_tor.txt -O - | sort -u >> block_tor.txt
    - name: Commit & Push changes
      uses: rblaine95/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
